# Generated by Django 5.1.1 on 2024-11-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_portfolio', models.CharField(max_length=255)),
                ('content_portfolio', models.TextField(null=True)),
                ('status_portfolio', models.BooleanField(default=False)),
                ('published_date_portfolio', models.DateTimeField(null=True)),
                ('created_date_portfolio', models.DateTimeField(auto_now_add=True, null=True)),
                ('updates_date_portfolio', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
