# Generated by Django 5.1.1 on 2024-11-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='content_view_portfolio',
            field=models.TextField(null=True),
        ),
    ]
