# Generated by Django 5.1.1 on 2024-11-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_content_view_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='content_view_portfolio',
            field=models.IntegerField(default=0),
        ),
    ]
